/* Generado por el motor de Cero Vagos. No editar a mano. */
window.CERO_VAGOS = {
 "generado": "2026-08-05T02:55:20",
 "total": 33,
 "stats": {
  "total_procesadas": 1207,
  "aprobadas_vigentes": 33,
  "tasa_aprobacion": 2.7,
  "sin_sueldo": 908,
  "pct_sin_sueldo": 75,
  "sueldo_mediano": 1500,
  "por_fuente": {
   "Bumeran": 32,
   "Convocatorias del Estado": 1
  }
 },
 "ofertas": [
  {
   "id": 1,
   "puesto": "Asesor(a) de Ventas",
   "empresa": "CoverPrime",
   "cat": "Atención al Cliente",
   "min": 1500,
   "max": 1500,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 3,
   "vence": "2026-10-31",
   "restan": 87,
   "score": 92,
   "resumen": "Buscamos una persona proactivo(a) y organizado(a) para unirse a nuestro equipo. El candidato ideal tendrá experiencia en atención al cliente, gestión de ventas y logística de despacho.",
   "funciones": [
    "Gestionar y dar seguimiento via WhatsApp, llamadas y correo electrónico, para realizar cotizaciones, venta y cierre de negocios de los productos/servicios de la empresa.",
    "Realizar el seguimiento de propuestas y coordinar con las áreas de logística y técnica para asegurar una entrega impecable del servicio/producto.",
    "Coordinar con Facturación para validar los depósitos de los pedidos realizados",
    "Gestionar y ampliar la cartera de clientes actuales actualizando la base de datos",
    "Cumplir metas de ventas establecidas y reportar avances al área comercial.",
    "Capacitaciones permanentes en la línea de producto, feedback con el staff de ejecutivo",
    "Seguimiento de leads en el CRM, elaboración de contratos y gestión de instalaciones.",
    "Manejo de consultas y requerimientos post-venta para asegurar la satisfacción del cliente."
   ],
   "requisitos": [
    "Experiencia mínima de 1 a 2 años en el rubro industrial",
    "Técnico y/o Universitario completo o inconcluso",
    "Experiencia de 1 a 2 años en posiciones de ventas y atención al cliente",
    "Experiencia en venta de productos textiles industriales, estructuras metálicas o similares (deseable).",
    "Habilidades de comunicación, persuasión y negociación",
    "Manejo del Office (Word, Excel PPT, Outlook) a nivel Intermedio",
    "De preferencia vivir a zonas aledañas a la Victoria",
    "Horario de trabajo de 8 a 6pm de lunes a viernes",
    "Excelente capacidad de comunicación, persuasión y negociación.",
    "Actitud positiva, proactiva y con gran empatía.",
    "Pasión por las ventas y el logro de metas.",
    "Vocación de servicio y orientación al cliente."
   ],
   "beneficios": [
    "Sueldo base 1500 soles + Comisión escalonada según margen de venta",
    "Disponibilidad a gozar 2 medio días libres al año para lo que gustes (cumpleaños, trámite, etc)",
    "Disponibilidad de 1 día al año para que realices tu examen oncológico preventivo",
    "Bonos por proyectos institucionales o de alto volumen y/o cumplimiento de objetivos",
    "Línea de carrera en el área",
    "Respaldo técnico y operativo",
    "PLanilla todos los beneficios en regimen REMYPE",
    "En Cover prime S.A.C. promovemos una cultura inclusiva, basada en el respeto, la diversidad y la equidad de oportunidades para todos. Fomentamos la participación de personas con discapacidad, en cumplimiento de la Ley N.° 29973, y aseguramos igualdad de condiciones para todos."
   ],
   "url": "https://www.bumeran.com.pe/empleos/asesora-de-ventas-b2b-sector-industrial-coverprime-1118387558.html"
  },
  {
   "id": 2,
   "puesto": "Anfitriona Automotriz A1",
   "empresa": "A&RC Consultores",
   "cat": "Tecnología",
   "min": 2700,
   "max": 2700,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 3,
   "vence": "2026-10-01",
   "restan": 57,
   "score": 92,
   "resumen": "Dar la bienvenida a los clientes y/o Ejecutivos de la compañía.",
   "funciones": [
    "Dar la bienvenida a los clientes y/o Ejecutivos de la compañía.",
    "Atención a clientes de nuestros productos y/o a ejecutivos de la compañía en red de concesionarias y/o Malls, dar bienvenida, información, dirigirlos a sus lugares en eventos corporativos.",
    "Salir en fotografías de catálogo, y/o eventos promocionales, participar en desfiles temáticos, etc.",
    "Dar cotizaciones, presupuestos, etc. (se les dará capacitación orientada, pagada desde el primer día)",
    "Opcional proceso de venta de vehículo con comisiones adicionales al sueldo ofrecido, por auto colocado.",
    "Participar en desfiles en eventos promocionales, de realizarse"
   ],
   "requisitos": [
    "Edad: Hasta 34 años",
    "Buena Presencia y Figura (NO Excluyente)",
    "Orientadas a la excelencia del servicio",
    "Proactiva y buen trato al cliente.",
    "Deseos de superación y trabajo en equipo.",
    "Personalidad extrovertida, conversadora, carismática y muy sociable.",
    "Disponibilidad de traslado a cualquier punto de lima. (facilidad de elegir cercanía a domicilio y/o centro de estudios)",
    "Ser atenta, servicial, amable y siempre disponible en cualquier actividad que se le encomiende.",
    "Rapidez e iniciativa.",
    "No requiere experiencia (capacitaciones constantes).",
    "Disponibilidad inmediata.",
    "Las Srtas. Interesadas, Postular enviando su CV con FOTOGRAFIA ACTUALIZADA, a arc.seleccion en gmail. com y asunto ANFIAUTO-2026. y por favor confirmar postulación por whatsapp con asistente de selección de personal, Srta. Andrea Garcés al Whatsapp +51 933 089 161 ."
   ],
   "beneficios": [
    "Ingreso a planillas con todos sus beneficios de ley desde el primer día de Capacitación.",
    "Oportunidad de desarrollar una Línea de Carrera",
    "Asignación familiar de tener hijos menores de edad",
    "Salario: Salario + viáticos semanales = S/. 2700 / mes",
    "Se dará Facilidades con sus horarios a las chicas que estudien.",
    "Horario y Contacto",
    "Mier, Jue, Vie, Sab de 9:30am a 5:30pm (Incluye refrigerio) y dos domingos al mes en el mismo horario."
   ],
   "url": "https://www.bumeran.com.pe/empleos/anfitriona-automotriz-a1-2026-marcas-de-autos-arc-consultores-1118387561.html"
  },
  {
   "id": 3,
   "puesto": "Arquitecto(a) Supervisor de Obra",
   "empresa": "CoverPrime",
   "cat": "Ingeniería",
   "min": 2500,
   "max": 2500,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 3,
   "vence": "2026-10-31",
   "restan": 87,
   "score": 89,
   "resumen": "COVER PRIME SAC es una empresa peruana que brinda servicios de fabricación e instalación de todo tipo de coberturas para exteriores, con planes de crecimiento. Nos encontramos en busca del mejor talento para el puesto de SUPERVISOR DE OBRA",
   "funciones": [
    "Supervisar la ejecución de trabajos arquitectónicos y acabados, asegurando el cumplimiento de planos, especificaciones técnicas y estándares de calidad.",
    "Coordinar con la constructora, contratistas y especialidades para prevenir y resolver interferencias durante la obra.",
    "Coordinar y dirigir al personal interno en obra",
    "Verificar el avance de obra y el cumplimiento del cronograma, realizando seguimiento a la programación diaria.",
    "Gestionar la logística y los recursos necesarios para la obra.",
    "Controlar la calidad de materiales, acabados y procedimientos constructivos, gestionando oportunamente las observaciones.",
    "Administrar y mantener actualizados los planos, cambios, documentación técnica y reportes de obra."
   ],
   "requisitos": [
    "Observador y detallista",
    "Comunicación efectiva a todo nivel tanto con cliente externo como interno",
    "Proactividad y orientación a resultados.",
    "Capacidad para en equipo y bajo presión",
    "Capacidad para resolución de problemas."
   ],
   "beneficios": [
    "Ingreso a planilla",
    "Todos los beneficios de ley",
    "Capacitación constante",
    "Línea de carrera a futuro dentro de la empresa",
    "Agradable ambiente laboral",
    "Remuneración bruta de S/.2500",
    "¡te invitamos a postular y ser parte de COVERPRIME y crecer juntos!"
   ],
   "url": "https://www.bumeran.com.pe/empleos/arquitectoa-supervisor-de-obra-coverprime-1118387541.html"
  },
  {
   "id": 4,
   "puesto": "Customer Service",
   "empresa": "CHAMBA TALENT S.A.C.",
   "cat": "Atención al Cliente",
   "min": 1700,
   "max": 2200,
   "modalidad": "Remoto",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 4,
   "vence": "2026-10-30",
   "restan": 86,
   "score": 95,
   "resumen": "¡Únete a una empresa líder en servicios de atención al cliente para importantes marcas internacionales!",
   "funciones": [
    "Brindar atención y soporte a clientes en inglés y español.",
    "Resolver consultas, incidencias y solicitudes a través de llamadas, correos electrónicos y otras plataformas de atención.",
    "Garantizar una experiencia de servicio eficiente y de calidad.",
    "Registrar información y realizar seguimiento a los casos asignados."
   ],
   "requisitos": [
    "Inglés intermedio avanzado a avanzado (B2, B2+ o C1 según campaña).",
    "Excelente comunicación verbal y escrita.",
    "Disponibilidad para trabajar de manera presencial en Miraflores.",
    "Deseable experiencia previa en atención al cliente.",
    "Para algunas campañas, se requiere ser mayor de 21 años.",
    "Capacitación remunerada.",
    "Duración entre 3 y 4 semanas, según la campaña asignada.",
    "Horarios de capacitación de lunes a sábado en horario diurno.",
    "Horarios de Operación",
    "Disponibilidad para laborar de lunes a domingo.",
    "Jornadas de 45 o 48 horas semanales según campaña.",
    "Entre 1 y 2 días de descanso por semana."
   ],
   "beneficios": [
    "Sueldo entre S/ 1,700 y S/ 2,200 según campaña y nivel de inglés.",
    "Bono de alimentación de S/ 260.",
    "Bono variable o bono por desempeño de hasta 15%.",
    "Capacitación pagada.",
    "Excelente ambiente laboral.",
    "Oportunidades de crecimiento y desarrollo profesional."
   ],
   "url": "https://www.bumeran.com.pe/empleos/customer-service-interprete-ingles-avanzado-remoto-chamba-talent-s.a.c.-1118387141.html"
  },
  {
   "id": 5,
   "puesto": "Asistente de Tesoreria",
   "empresa": "CoverPrime",
   "cat": "Tecnología",
   "min": 1500,
   "max": 1500,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 4,
   "vence": "2026-10-30",
   "restan": 86,
   "score": 95,
   "resumen": "Garantizar el cumplimiento oportuno de las obligaciones financieras de la empresa (pagos a proveedores, entidades bancarias, nómina, entre otros).",
   "funciones": [
    "Garantizar el cumplimiento oportuno de las obligaciones financieras de la empresa (pagos a proveedores, entidades bancarias, nómina, entre otros).",
    "Manejo de plataforma de bancos.",
    "Gestionar y actualizar el flujo de caja diario y semanal.",
    "Mantener ordenado actualizados los registros de tesorería y bancos.",
    "Conciliaciones bancarias por centro de costo y partidas de presupuesto.",
    "Apoyar en la coordinación con las áreas de Contabilidad y Operaciones Logísticas para validar facturas, impuestos, fechas de pago y vencimientos, asegurando el cumplimiento de los compromisos financieros.",
    "Elaborar proyecciones de liquidez y flujo de efectivo de manera quincenal",
    "Elaborar reportes financieros y de tesorería de manera mensual",
    "Proponer mejoras en los procesos y controles del área.",
    "Otras funciones asignadas por su jefe inmediato."
   ],
   "requisitos": [
    "Bachiller/Egresado de las carreras de Contabilidad, Economía, Administración, finanzas o carreras afines del área financiera. (INDISPENSABLE).",
    "Contar con 1 año de experiencia mínima en el área de contabilidad, finanzas o tesorería",
    "Manejo de Office a nivel avanzado.",
    "Manejo de plataformas bancarias",
    "Experiencia comprobable en manejo de caja chica y conciliaciones bancarias",
    "Disponibilidad inmediata",
    "Horario de lunes a viernes de 09:00 a.m. a 06:00 p.m. y sábados de 09:00 a.m. a 01:00 p.m en nuestra oficina ubicado en el distrito de la victoria",
    "Responsabilidad y confidencialidad en el manejo de información.",
    "Comunicación efectiva.",
    "Proactividad y orientación a resultados.",
    "Excelentes habilidades analíticas y de organización.",
    "Capacidad para trabajar de forma autónoma y colaborativa."
   ],
   "beneficios": [
    "Ingreso a planilla desde el primer día",
    "Todos los beneficios de ley",
    "Posibilidad de capacitación constante",
    "Línea de carrera a futuro dentro de la empresa",
    "Agradable ambiente laboral",
    "Remuneración de S/.1500",
    "Si te apasiona el análisis financiero y deseas contribuir al crecimiento de una organización comprometida con aumentar la calidad de vida de las personas, ¡te invitamos a postular y ser parte de COVERPRIME!"
   ],
   "url": "https://www.bumeran.com.pe/empleos/asistente-de-tesoreria-coverprime-1118387435.html"
  },
  {
   "id": 6,
   "puesto": "Asesor de Seguros Vida",
   "empresa": "Rimac Cia de Seguros y Reaseguros S.A.",
   "cat": "Tecnología",
   "min": 4000,
   "max": 4000,
   "modalidad": "Presencial",
   "ciudad": "Cusco",
   "fuente": "Bumeran",
   "dias": 4,
   "vence": "2026-11-29",
   "restan": 116,
   "score": 94,
   "resumen": "📣* POSTULA POR AQUÍ * https://form.typeform.com/to/lAiV4DJa (copia y pega el link en otra ventana)",
   "funciones": [
    "Desarrollar y mantener relaciones con los clientes.",
    "Identificar y evaluar las necesidades de seguros de los clientes.",
    "Brindar servicio al cliente y resolver problemas.",
    "Recomendar y vender pólizas de seguros que satisfagan las necesidades de los clientes.",
    "Participar continuamente en los procesos de mejora de gestión."
   ],
   "requisitos": [
    "Experiencia mínima de 6 meses en ventas de intangibles o ATC (seguros, servicios financieros, telecomunicaciones, venta de vehículos o inmobiliarias).",
    "Cartera de clientes o red de contacto activa (indispensable).",
    "Manejo de herramientas digitales"
   ],
   "beneficios": [
    "Planilla RIMAC desde el primer día",
    "Remuneración variable, sin tope de comisiones, desde S/4000 al 100% de cumplimiento.",
    "EPS al 90% para titular, cónyuge e hijos. Adicional, un plan especial para padres.",
    "Bonos, viajes y campañas.",
    "📣* POSTULA POR AQUÍ * https://form.typeform.com/to/lAiV4DJa (copia y pega el link en otra ventana)",
    "En Rimac Seguros y Reaseguros estamos comprometidos con la igualdad de oportunidades y derechos. Todas las personas que postulen a nuestras vacantes serán consideradas sin importar su origen, género, discapacidad, edad o cualquier otra característica, condición o preferencia."
   ],
   "url": "https://www.bumeran.com.pe/empleos/asesor-de-seguros-vida-cusco-rimac-cia-de-seguros-y-reaseguros-s.a.-1118387151.html"
  },
  {
   "id": 7,
   "puesto": "Asesor de Seguros Vida",
   "empresa": "Rimac Cia de Seguros y Reaseguros S.A.",
   "cat": "Tecnología",
   "min": 4000,
   "max": 4000,
   "modalidad": "Presencial",
   "ciudad": "Piura",
   "fuente": "Bumeran",
   "dias": 4,
   "vence": "2026-11-28",
   "restan": 115,
   "score": 94,
   "resumen": "📣* POSTULA POR AQUÍ * https://form.typeform.com/to/lAiV4DJa (copia y pega el link en otra ventana)",
   "funciones": [
    "Desarrollar y mantener relaciones con los clientes.",
    "Identificar y evaluar las necesidades de seguros de los clientes.",
    "Brindar servicio al cliente y resolver problemas.",
    "Recomendar y vender pólizas de seguros que satisfagan las necesidades de los clientes.",
    "Participar continuamente en los procesos de mejora de gestión."
   ],
   "requisitos": [
    "Experiencia mínima de 6 meses en ventas de intangibles o ATC (seguros, servicios financieros, telecomunicaciones, venta de vehículos o inmobiliarias).",
    "Cartera de clientes o red de contacto activa (indispensable).",
    "Manejo de herramientas digitales"
   ],
   "beneficios": [
    "Planilla RIMAC desde el primer día",
    "Remuneración variable, sin tope de comisiones, desde S/4000 al 100% de cumplimiento.",
    "EPS al 90% para titular, cónyuge e hijos. Adicional, un plan especial para padres.",
    "Bonos, viajes y campañas.",
    "📣* POSTULA POR AQUÍ * https://form.typeform.com/to/lAiV4DJa (copia y pega el link en otra ventana)",
    "En Rimac Seguros y Reaseguros estamos comprometidos con la igualdad de oportunidades y derechos. Todas las personas que postulen a nuestras vacantes serán consideradas sin importar su origen, género, discapacidad, edad o cualquier otra característica, condición o preferencia."
   ],
   "url": "https://www.bumeran.com.pe/empleos/asesor-de-seguros-vida-piura-rimac-cia-de-seguros-y-reaseguros-s.a.-1118387154.html"
  },
  {
   "id": 8,
   "puesto": "Operaria de Producción",
   "empresa": "CYL",
   "cat": "Ingeniería",
   "min": 1150,
   "max": 1150,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 4,
   "vence": "2026-09-30",
   "restan": 56,
   "score": 94,
   "resumen": "¡TRABAJA EN PRODUCCIÓN – INGRESO RÁPIDO!",
   "funciones": [
    "Manejo de las máquinas de varias (anillado-habilitado-corte-caucho y operaciones manuales).",
    "Mantener su puesto de trabajo limpio y ordenado.",
    "Cumplir con las normas de calidad y seguridad y reglamento interno de trabajo dentro de la planta.",
    "Conocer las rutas de evacuación.",
    "Cumplir los instructivos de trabajo"
   ],
   "requisitos": [
    "Secundaria completa",
    "Disponibilidad de horas extra.",
    "Disponibilidad para turno rotativos",
    "Turno 1 Lunes a Viernes de 7 am a 4:15 pm y sábados de 7 am a 12:30 pm",
    "Turno 2 Lunes a Viernes de 9 am a 7:15 pm."
   ],
   "beneficios": [
    "Ingreso a planilla directo (todos los beneficios+SSALUD+ASIGNACION FAMILIAR+UTILIDADES)",
    "Bono de transporte + bono por asistencia",
    "Sueldo s/1150.00 aumenta al año s/1180. 00",
    "Alimentación un 70% cubierto",
    "Buen clima laboral"
   ],
   "url": "https://www.bumeran.com.pe/empleos/operaria-de-produccion-maquinaria-con-o-sin-experiencia-santa-anita-cyl-1118387178.html"
  },
  {
   "id": 9,
   "puesto": "Asesor de Seguros Vida",
   "empresa": "Rimac Cia de Seguros y Reaseguros S.A.",
   "cat": "Tecnología",
   "min": 4000,
   "max": 4000,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 4,
   "vence": "2026-10-30",
   "restan": 86,
   "score": 94,
   "resumen": "📣* POSTULA POR AQUÍ * https://form.typeform.com/to/lAiV4DJa (copia y pega el link en otra ventana)",
   "funciones": [
    "Desarrollar y mantener relaciones con los clientes.",
    "Identificar y evaluar las necesidades de seguros de los clientes.",
    "Brindar servicio al cliente y resolver problemas.",
    "Recomendar y vender pólizas de seguros que satisfagan las necesidades de los clientes.",
    "Participar continuamente en los procesos de mejora de gestión."
   ],
   "requisitos": [
    "Experiencia mínima de 6 meses en ventas de intangibles o ATC (seguros, servicios financieros, telecomunicaciones, etc.).",
    "Cartera de clientes o red de contacto activa (indispensable).",
    "Manejo de herramientas digitales"
   ],
   "beneficios": [
    "Planilla RIMAC desde el primer día",
    "Remuneración variable, sin tope de comisiones, desde S/4000 al 100% de cumplimiento.",
    "EPS al 90% para titular, cónyuge e hijos. Adicional, un plan especial para padres.",
    "Bonos, viajes y campañas.",
    "📣* POSTULA POR AQUÍ * https://form.typeform.com/to/lAiV4DJa (copia y pega el link en otra ventana)",
    "En Rimac Seguros y Reaseguros estamos comprometidos con la igualdad de oportunidades y derechos. Todas las personas que postulen a nuestras vacantes serán consideradas sin importar su origen, género, discapacidad, edad o cualquier otra característica, condición o preferencia."
   ],
   "url": "https://www.bumeran.com.pe/empleos/asesor-de-seguros-vida-lima-norte-rimac-cia-de-seguros-y-reaseguros-s.a.-1118387324.html"
  },
  {
   "id": 10,
   "puesto": "Operario de Limpieza de Piezas",
   "empresa": "CYL",
   "cat": "Ingeniería",
   "min": 1150,
   "max": 1150,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 4,
   "vence": "2026-09-30",
   "restan": 56,
   "score": 91,
   "resumen": "¡VACANTES DISPONIBLES YA! – INGRESO INMEDIATO",
   "funciones": [
    "Limpieza y conteo de piezas durante el proceso de producción",
    "Apoyo a operarios de máquina",
    "Mantener el orden y limpieza del área de trabajo",
    "Cumplir con normas de calidad y seguridad",
    "Trabajo dentro de planta"
   ],
   "requisitos": [
    "Secundaria completa",
    "Con o sin experiencia",
    "Disponibilidad para realizar horas extras",
    "Actitud para aprender y adaptarse al área de producción",
    "Disponibilidad para turno rotativos",
    "Turno 1 Lunes a Viernes de 7 am a 4:15 pm y sábados de 7 am a 12:30 pm",
    "Turno 2 Lunes a Viernes de 9 am a 7:15 pm."
   ],
   "beneficios": [
    "Ingreso a planilla directa con todos los beneficios de ley",
    "Bono de transporte + bono por asistencia",
    "Sueldo S/ 1150.00 con incremento a S/ 1180.00 al cumplir un año",
    "Alimentación cubierta al 70%",
    "Buen clima laboral y oportunidades de crecimiento"
   ],
   "url": "https://www.bumeran.com.pe/empleos/operario-de-limpieza-de-piezas-produccion-santa-anita-cyl-1118387172.html"
  },
  {
   "id": 11,
   "puesto": "Asistente de Marketing y Comercial",
   "empresa": "CoverPrime",
   "cat": "Tecnología",
   "min": 1500,
   "max": 1500,
   "modalidad": "Híbrido",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 4,
   "vence": "2026-10-30",
   "restan": 86,
   "score": 89,
   "resumen": "Crear y editar videos para las distintas redes sociales",
   "funciones": [
    "Crear y editar videos para las distintas redes sociales",
    "Crear artículos para linkedin",
    "Crear los copys y contenido cumpliendo con el cronograma de publicaciones en las distintas redes sociales (Facebook, LinkedIn, YouTube, Instagram, tiktok, pinterest) e historias",
    "Participar en videos promocionales según sea necesario",
    "Dar seguimiento operativo al CRM: asignación de leads, monitoreo del embudo comercial y control de calidad de la información registrada detectando tendencia de compra, realización de compra cruzada",
    "Monitorear los precios del mercado para proponer ajustes estratégicos que aumenten la competitividad.",
    "Creación de flyer o promociones para el área comercial",
    "Elaborar y mantener actualizado los catálogos de productos y servicios",
    "Elaborar reportes de ventas para medir el cumplimiento de las metas comerciales.",
    "Responder consultas en las diferentes redes sociales",
    "Prospección de nuevas oportunidades de mercado y tendencias.",
    "Apoyo en la creación de promociones y publicidad en general."
   ],
   "requisitos": [
    "Estudios técnicos o universitarios concluidos en las carreras de Ciencias de la Comunicación, Marketing, Administración o carreras afines",
    "Manejo de Ilustrator, Photoshop, Premiere Pro, Indesign a nivel intermedio, Capcut y herramientas de IA",
    "Manejo de Ms Office a nivel intermedio para reportes y de Google drive",
    "Disponibilidad para realizar toma de fotos en toda lima metropolitana o fuera de lima cuando se requiera (viáticos cubiertos)",
    "Mínimo 2 años de experiencia en la posición de Auxiliar o Asistente de Marketing o puestos afines, en el sector construcción, inmobiliaria o afines (deseable)",
    "Trabajo Hibrido: Disponibilidad para trabajar 2 o 3 días a la semana rotativos en oficina en La victoria de lunes a viernes de 09:00 a.m. a 06:00 p.m. y sábados de 09:00 a.m. a 01:00 p.m.",
    "Disponibilidad para trabajar desde 1 de setiembre",
    "Alto sentido de responsabilidad, orden y criterio lógico",
    "Capacidad de aprendizaje rápido",
    "Capacidad para trabajar de forma autónoma y en equipo.",
    "Capacidad de planificación y organización",
    "Comunicación a todo nivel"
   ],
   "beneficios": [
    "Línea de carrera a futuro dentro de la empresa",
    "Ambiente de trabajo dinámico y enfocado en la excelencia",
    "Remuneración 1500 soles",
    "Ingreso a planilla bajo régimen MYPE con todos los beneficios de ley",
    "Flexibilidad de horario"
   ],
   "url": "https://www.bumeran.com.pe/empleos/asistente-de-marketing-y-comercial-coverprime-1118387417.html"
  },
  {
   "id": 12,
   "puesto": "Asesor de Ventas",
   "empresa": "CAMARA DE COMERCIO EXTERIOR S.A.C.",
   "cat": "Ventas",
   "min": 1200,
   "max": 1200,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 4,
   "vence": "2026-10-30",
   "restan": 86,
   "score": 84,
   "resumen": "¿Buscas un lugar donde crecer y ganar bien? ¡Esta es tu oportunidad! En CE buscamos personas con energía, buena comunicación y ganas de vender, para sumarse a nuestro equipo comercial.",
   "funciones": [
    "Atender a nuestros clientes por redes sociales.",
    "Darles a nuestros clientes la información de los productos de su interés.",
    "Hacer el seguimiento al cliente de su curso de interés por nuestra redes sociales."
   ],
   "requisitos": [
    "Habilidades de comunicación",
    "Actitud positiva y orientación a resultados",
    "Ganas de aprender y crecer con nosotros",
    "Lunes a Sábado de 2:00 pm - 10:45 pm.",
    "Lugar: San Isidro | Presencial | Tiempo completo",
    "📌 Apto para personas con discapacidad",
    "¡Si te apasionan las ventas y quieres formar parte de un equipo ganador, postula ahora!"
   ],
   "beneficios": [
    "💰 Sueldo base S/1,200 + Comisiones atractivas todas las semanas",
    "🚌 Bono de movilidad de S/200",
    "🚇 Fácil acceso por el Corredor Rojo (Javier Prado) y cerca a la estación Canaval y Moreyra del Metropolitano",
    "🤝 Excelente ambiente laboral, con un equipo que te acompaña",
    "📚 Capacitaciones constantes para que sigas creciendo profesionalmente",
    "🧘 Pausas activas durante tu jornada",
    "☕ Café los miércoles y 🍿 canchita los viernes, ¡para hacer tu semana más amena!"
   ],
   "url": "https://www.bumeran.com.pe/empleos/unete-a-nuestro-equipo-de-ventas-asesor-de-ventas--turno-tarde-camara-de-comercio-exterior-s.a.c.-1118387337.html"
  },
  {
   "id": 13,
   "puesto": "Coordinador de Mantenimiento",
   "empresa": "Pigmalion Consultores",
   "cat": "Ingeniería",
   "min": 2500,
   "max": 3000,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-09-29",
   "restan": 55,
   "score": 100,
   "resumen": "Si se encuentra interesado(a), debe enviar su CV al siguiente número: 933 429 319",
   "funciones": [
    "Planificar, coordinar y supervisar el mantenimiento preventivo y correctivo de la planta.",
    "Gestionar el correcto funcionamiento de equipos eléctricos y mecánicos.",
    "Elaborar y dar seguimiento a indicadores e informes de mantenimiento.",
    "Gestionar la compra y cotización de repuestos e insumos necesarios para el área.",
    "Coordinar con el equipo de producción la ejecución de los mantenimientos para asegurar la continuidad de la operación.",
    "Apoyar en la supervisión de personal técnico y promover el cumplimiento de los estándares de seguridad."
   ],
   "requisitos": [
    "Técnico o Egresado en Ingeniería Mecánica o similares.",
    "Entre 1 a 2 años de experiencia en mantenimiento industrial.",
    "Conocimiento en mantenimiento de máquinas envasadoras, hornos y equipos que tengan PLC.",
    "Conocimiento en compras de repuestos y gestión de cotizaciones.",
    "Experiencia en empresas del rubro de alimentos. (Deseable)",
    "Disponibilidad para laborar en San Luis, Lima Perú."
   ],
   "beneficios": [
    "Planilla desde primer día bajo Régimen MYPE",
    "Sueldo entre S/. 2500 – S/. 3000",
    "Asignación familiar según ley",
    "Capacidad de realizar horas extras.",
    "Bonos de Movilidad y Alimentación",
    "Ubicación: San Luis, frente al Mercado de fruta."
   ],
   "url": "https://www.bumeran.com.pe/empleos/coordinador-de-mantenimiento-wimpon-pigmalion-consultores-1118386015.html"
  },
  {
   "id": 14,
   "puesto": "Ingeniero de Proyectos Gestión SSOMA",
   "empresa": "Engineering Services & Consulting S.A.C",
   "cat": "Ingeniería",
   "min": 2500,
   "max": 2500,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 97,
   "resumen": "Apoyar en la planificación, ejecución y seguimiento de los proyectos SSOMA.",
   "funciones": [
    "Apoyar en la planificación, ejecución y seguimiento de los proyectos SSOMA.",
    "Coordinar los recursos necesarios para la correcta ejecución de los servicios.",
    "Realizar el seguimiento al personal destacado en campo y al cumplimiento de los entregables.",
    "Elaborar informes, reportes y documentación técnica para clientes.",
    "Verificar el cumplimiento de la normativa vigente, los requisitos del cliente y los estándares de SINCRO.",
    "Participar en reuniones de coordinación con clientes, proveedores y equipos internos.",
    "Brindar soporte en la elaboración de propuestas técnicas, cotizaciones y procesos de licitación.",
    "Mantener actualizada la documentación técnica y administrativa de los proyectos."
   ],
   "requisitos": [
    "Bachiller de Ingeniería Industrial, Ingeniería de Seguridad, Ingeniería Ambiental, Ingeniería de Minas, Ingeniería Civil, Ingeniería Química o carreras afines.",
    "Deseable título profesional y colegiatura.",
    "Experiencia mínima de 2 años en SSOMA, SST, HSE/EHS o Sistemas Integrados de Gestión.",
    "Experiencia en gestión y seguimiento de proyectos o servicios SSOMA.",
    "Conocimiento de la Ley N.° 29783, IPERC, trabajos de alto riesgo y Sistemas de Gestión ISO 45001, ISO 14001 e ISO 9001.",
    "Manejo de Microsoft Office a nivel intermedio.",
    "Deseable experiencia en elaboración de propuestas técnicas, licitaciones y coordinación con clientes y proveedores.",
    "Deseable conocimiento de herramientas de inteligencia artificial aplicadas a la gestión documental y análisis de información.",
    "Disponibilidad para realizar visitas a campo según requerimiento."
   ],
   "beneficios": [
    "Ubicación: Surquillo, Lima",
    "Horario: Lunes a viernes de 8:30 a.m. a 5:30 p.m.",
    "Remuneración: S/ 2,500",
    "Ingreso a planilla desde el primer día con todos los beneficios de ley",
    "EPS cubierta al 50% y Seguro Oncológico al 100%",
    "Seguro Vida Ley desde el primer día de labores",
    "Participación en utilidades",
    "Acceso a capacitaciones constantes y oportunidades de aprendizaje continuo",
    "Participación en proyectos de alto impacto con clientes líderes",
    "Grato ambiente laboral y actividades de integración",
    "Pertenecer a una empresa líder y en constante crecimiento",
    "¡Sé parte del equipo SINCRO y lleva tu talento al siguiente nivel!"
   ],
   "url": "https://www.bumeran.com.pe/empleos/ingeniero-de-proyectos-gestion-ssoma-engineering-services-consulting-s.a.c-1118386028.html"
  },
  {
   "id": 15,
   "puesto": "Asesor(a) de ventas San Isidro",
   "empresa": "ADECCO",
   "cat": "Ventas",
   "min": 1300,
   "max": 2000,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 95,
   "resumen": "En Adecco, por encargo de nuestro cliente Cámara de Comercio Exterior , nos encontramos en la búsqueda de Asesor(a) de Ventas Digitales - San Isidro con experiencia en ventas y enfoque a resultados.",
   "funciones": [
    "Asesorar y vender cursos digitales a clientes potenciales.",
    "Gestionar leads provenientes de diferentes canales digitales.",
    "Atender consultas a través de chat y otros medios de contacto.",
    "Realizar seguimiento comercial hasta el cierre de la venta.",
    "Brindar soporte al cliente respecto a accesos e inicio de cursos."
   ],
   "requisitos": [
    "Secundaria completa, estudios técnicos o universitarios en curso.",
    "Experiencia mínima de 6 meses en Ventas digitales, Call Center, Ventas directas o Atención comercial.",
    "Manejo de herramientas digitales y seguimiento comercial.",
    "Disponibilidad para trabajar en San Isidro.",
    "Excelente comunicación, proactividad y orientación a resultados."
   ],
   "beneficios": [
    "Sueldo fijo: S/ 1,200.",
    "Atractivas comisiones semanales desde la primera semana.",
    "Ingresos variables aproximados entre S/ 1,300 y S/ 2,000 adicionales según desempeño.",
    "Capacitación y oportunidades de crecimiento",
    "Lugar de trabajo: San Isidro.",
    "Horario: Lunes a sábado de 2:00 p.m. a 10:45 p.m. (45 minutos de refrigerio).",
    "Modalidad: Presencial.",
    "Contrato bajo régimen MYPE"
   ],
   "url": "https://www.bumeran.com.pe/empleos/asesora-de-ventas-san-isidro-adecco-1118386014.html"
  },
  {
   "id": 16,
   "puesto": "Administrador de Operaciones",
   "empresa": "Beliving Talents",
   "cat": "Contabilidad",
   "min": 2000,
   "max": 2500,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-09-29",
   "restan": 55,
   "score": 95,
   "resumen": "ENVIA TU CV: 922 - 054 - 346 (UNICO MEDIO DE RECEPCION)",
   "funciones": [
    "Gestionar la emisión de comprobantes de pago mediante plataformas ERP y SUNAT.",
    "Realizar seguimiento y control de comprobantes emitidos.",
    "Revisar cuentas de clientes, identificando pagos pendientes, realizados y diferencias por regularizar.",
    "Gestionar la recepción y validación de documentos para la generación de cuentas por pagar.",
    "Realizar seguimiento de obligaciones pendientes y programación de pagos, asegurando el cumplimiento de plazos.",
    "Gestionar información bancaria de clientes (movimientos, estados de cuenta, carga de documentos e instrucciones operativas).",
    "Elaborar reportes administrativos y financieros sobre pagos, saldos pendientes y disponibilidad de fondos."
   ],
   "requisitos": [
    "Técnico, Bachiller o Licenciado en Administración, Ingeniería Industrial, Contabilidad o carreras afines.",
    "Experiencia mínima de 3 años en áreas administrativas, especialmente en gestión de tesorería y facturación.",
    "Experiencia en outsourcing.",
    "Manejo de Excel intermedio – avanzado.",
    "Deseable nivel de inglés intermedio – avanzado."
   ],
   "beneficios": [
    "Ubicación: Magdalena del Mar (Av. Del Ejército).",
    "Horario: Lunes a viernes de 9:00 a.m. a 6:00 p.m.",
    "Régimen laboral: Planilla completa con todos los beneficios de ley.",
    "Remuneración: S/2000 a S/2500."
   ],
   "url": "https://www.bumeran.com.pe/empleos/administrador-de-operaciones-outsourcing-beliving-talents-1118386627.html"
  },
  {
   "id": 17,
   "puesto": "Practicante Profesional de Contabilidad",
   "empresa": "CENTAURO EDITORES SAC",
   "cat": "Contabilidad",
   "min": 1300,
   "max": 1600,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 95,
   "resumen": "Aprenderás a llevar la Contabilidad de la mano de una Contadora experta.",
   "funciones": [
    "Aprenderás a llevar la Contabilidad de la mano de una Contadora experta.",
    "Aprenderás a manejar Flujo de Caja de la mano de una Contadora experta",
    "Realizar cruce y validación de documentos: facturas, guías de remisión y pagos",
    "Detectar y reportar inconsistencias o diferencias",
    "Mantener orden y control documentario"
   ],
   "requisitos": [
    "Egresado(a) reciente de Contabilidad",
    "Alto nivel de orden y organización personal",
    "Responsabilidad en el cumplimiento de tareas y fechas",
    "Pensamiento lógico y estructurado Requisitos técnicos",
    "Manejo de Office a nivel intermedio, mínimo.",
    "Deseable conocimiento básico de documentos contables.",
    "Disponibilidad inmediata"
   ],
   "beneficios": [
    "Aprendizaje directo en gestión real de flujo de caja empresarial",
    "Formación práctica en control financiero",
    "Acompañamiento cercano en tu desarrollo",
    "Oportunidad de crecimiento según desempeño",
    "Grato ambiente de trabajo.",
    "La Empresa invita los almuerzos del día viernes",
    "Acuerdos de practicas con todo lo que la ley establece.",
    "Modalidad: Presencial (Lima)",
    "Subvención: S/ 1,300-1600 Postulación"
   ],
   "url": "https://www.bumeran.com.pe/empleos/practicante-profesional-de-contabilidad-centauro-editores-sac-1118386941.html"
  },
  {
   "id": 18,
   "puesto": "Auxiliar Operativo",
   "empresa": "Servicios Postales del Perú S.A.",
   "cat": "Tecnología",
   "min": 1130,
   "max": 1130,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 95,
   "resumen": "Carga y descarga de paquetes, encomiendas, sacas y documentación.",
   "funciones": [
    "Carga y descarga de paquetes, encomiendas, sacas y documentación.",
    "Traslado, ordenamiento y acondicionamiento de envíos dentro del área operativa.",
    "Recepción, clasificación y verificación de documentación y cargos.",
    "Apertura y despacho de cargos y documentación.",
    "Digitalización y registro de documentos en el sistema.",
    "Apoyo en actividades operativas propias de la distribución y procesamiento de envíos."
   ],
   "requisitos": [
    "Secundaria completa. (Indispensable)",
    "Manejo de base de datos: Excel nivel intermedio (deseable)",
    "Manejo de digitalización de documentos",
    "Experiencia mínima de 6 meses en actividades similares y afines a las descritas",
    "Experiencia en clasificación documentaria manual y electrónica",
    "Experiencia en atención al cliente (deseable)",
    "Disponibilidad para laborar en el distrito de Los Olivos"
   ],
   "beneficios": [
    "Ingreso a planilla con todos los beneficios de ley.",
    "Remuneración mensual de S/1130 soles.",
    "Horario de trabajo: Lunes a sabados (48 horas semanales)",
    "Alimentación cubierta al 50%",
    "Aquellos que cumplan con el perfil deberán ENVIAR su cv al correo de seleccion(arroba)serpost.com.pe"
   ],
   "url": "https://www.bumeran.com.pe/empleos/auxiliar-operativo-almacen-los-olivos-servicios-postales-del-peru-s.a.-1118387001.html"
  },
  {
   "id": 19,
   "puesto": "Representante de Servicios",
   "empresa": "CAJA CUSCO",
   "cat": "Tecnología",
   "min": 1380,
   "max": 1380,
   "modalidad": "Presencial",
   "ciudad": "Cusco",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-11-27",
   "restan": 114,
   "score": 94,
   "resumen": "Atender las operaciones de clientes y realizar la venta de servicios brindando un servicio de calidad, transparencia de información y guardando la confidencialidad de las operaciones e información de clientes garantizando la confidencialidad de información de los usuarios.",
   "funciones": [
    "Atender las operaciones de clientes y realizar la venta de servicios brindando un servicio de calidad, transparencia de información y guardando la confidencialidad de las operaciones e información de clientes garantizando la confidencialidad de información de los usuarios.",
    "Orientar a los clientes con información transparente sobre los productos y servicios que se ofrecen, brindando soluciones para asegurar una atención de calidad, cortesía a clientes y preservar una buena imagen institucional.",
    "Realizar la venta de servicios según las metas asignadas para el cumplimiento de objetivos de las Agencia y de la empresa.",
    "Realizar el cuadre de efectivo de forma diaria e informar en caso de identificar sobrantes o faltantes para cumplir con los procedimientos de control interno.",
    "Realizar actividades de control interno que aseguren que las operaciones se realicen cumpliendo los procedimientos internos y normas de entes supervisores, a fin de minimizar riesgos de sanciones."
   ],
   "requisitos": [
    "Experiencia al Cliente",
    "Espíritu Colaborativo",
    "Mejora Continua",
    "Profesional Técnico, Egresado, Bachiller o Estudios truncos de cualquier especialidad de Institutos o Universidades.",
    "Representante de servicios con categoría superior: Seis (6) meses en el mismo cargo o un (1) año como Auxiliar de Atención al Usuario y Calidad o Puestos equivalentes en empresas del Sistema Financiero.",
    "Representante de servicios junior: sin experiencia"
   ],
   "beneficios": [
    "Remuneración fija de S/. 1380.",
    "Tarjeta de alimentación trimestral.",
    "Oportunidad de Línea de carrera.",
    "Ingreso a planilla con todos los beneficios de ley.",
    "Opcional: Acceso a seguro privado de salud.",
    "Fecha límite de postulación: Domingo , 09 de Agosto del 2026"
   ],
   "url": "https://www.bumeran.com.pe/empleos/representante-de-servicios-agencia-puquio-ref-1308-2026-caja-cusco-1118386570.html"
  },
  {
   "id": 20,
   "puesto": "Operario de montaje",
   "empresa": "Estanterías Metálicas JRM S.A.C",
   "cat": "Logística",
   "min": 1800,
   "max": 2000,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 93,
   "resumen": "La empresa Estanterías Metálicas JRM👨🏻‍🏭🔩🙌🏻, - Somos una empresa especializada en el diseño y construcción de centros de distribución y operaciones logísticas",
   "funciones": [
    "Solicitar y disponer de las herramientas requeridas para la ejecución del montaje según procedimiento.",
    "Recepcionar y apoyar con la manipulación de los materiales y accesorios entregados a obra.",
    "Realizar el inventario de saldos de obra al finalizar la instalación.",
    "Conocer y aplicar los planes y respuestas a las emergencias establecidas en la organización."
   ],
   "requisitos": [
    "Experiencia mínima d e 6 meses a 1 año en trabajos de altura, estanterías y/o racks. (Comprobada)",
    "Disponibilidad para realizar trabajo físico.",
    "Personas proactivas y responsables con el trabajo.",
    "Disponibilidad para laborar en diferentes obras."
   ],
   "beneficios": [
    "Pago quincenal y mensual",
    "Sueldo superior al mercado (S/1800 - S/2000 segùn evaluaciòn del àrea)",
    "Pago de movilidad y almuerzo (S/340 mensuales)",
    "Adicional de condición de trabajo (S/200)",
    "Línea de carrera. * Convenios corporativos",
    "Ingreso a planilla desde el primer día con todo los beneficios de Ley al 100%.",
    "Trabajo de Lunes a Viernes (8-5:30) Sábado (8-1pm) - Posibilidad de hacer horas extras",
    "Puedes mandar tu CV al 989 304 973 RUTH INCA - O postular directamente por acá",
    "Puedes acercarte directamente de Lunes a viernes de 10am a 12:30 a Av las Américas 275, La Victoria"
   ],
   "url": "https://www.bumeran.com.pe/empleos/operario-de-montaje-urgente-estanterias-metalicas-jrm-s.a.c-1118386775.html"
  },
  {
   "id": 21,
   "puesto": "Supervisor Comercial Internacional",
   "empresa": "Talento Humano Perú",
   "cat": "Ventas",
   "min": 3000,
   "max": 3000,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 92,
   "resumen": "Nuestro cliente, Agencia Internacional especializada en la comercialización de Seguros de Vida, Salud e Inversiones, nos ha encargado la búsqueda de un (1) Supervisor Comercial Internacional de Seguros de Vida y Salud.",
   "funciones": [
    "Diseñar e implementar estrategias para el cumplimiento de metas de ventas.",
    "Gestionar el desempeño de la fuerza comercial mediante indicadores (KPIs).",
    "Brindar acompañamiento y coaching comercial al equipo de ventas.",
    "Prospectar y desarrollar nuevas oportunidades de negocio.",
    "Mantener y fortalecer relaciones con clientes corporativos e individuales.",
    "Elaborar reportes comerciales y proyecciones de ventas para la dirección.",
    "Coordinar campañas comerciales y actividades de capacitación.",
    "Garantizar el cumplimiento de las políticas y lineamientos comerciales de la compañía.",
    "Promover la comercialización de productos internacionales de Vida, Salud e Inversiones."
   ],
   "requisitos": [
    "Profesional universitario en Administración, Marketing, Economía, Ingeniería Comercial o carreras afines.",
    "Experiencia mínima de tres (3) años en posiciones comerciales a fines de sector.",
    "Experiencia en el área comercial relacionada a Seguros de Vida, Seguros de Salud, AFPs, Seguros Internacionales o relacionados.",
    "Experiencia liderando equipos de ventas o fuerza comercial.",
    "Ms. Office, nivel intermedio. • Inglés, nivel intermedio."
   ],
   "beneficios": [
    "Remuneración: $ 3,000.00 dólares + Comisiones.",
    "Contrato Honorarios Profesionales con empresa extranjera (Locador de Servicios - USA).",
    "Vacaciones al año: 12 días hábiles.",
    "MODALIDAD DE TRABAJO Y HORARIO DE MIAMI",
    "Lunes a viernes de 9:00 a.m. a 6:00 p.m.",
    "Distrito en San Isidro.",
    "Trabajo presencial."
   ],
   "url": "https://www.bumeran.com.pe/empleos/supervisor-comercial-internacional--seguros-de-vida-y-salud-talento-humano-peru-1118386040.html"
  },
  {
   "id": 22,
   "puesto": "Técnico de Farmacia para atención al cliente",
   "empresa": "Confidencial",
   "cat": "Atención al Cliente",
   "min": 1500,
   "max": 1500,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 92,
   "resumen": "Por encargado de nuestro cliente en el area de Farmacias nos encontramos en busqueda de un Técnico de Farmacia / Miraflores",
   "funciones": [
    "Dar seguimiento al paciente del canal asignado",
    "Gestionar, coordina de forma correcta la atención al paciente según lo indicado en su receta",
    "Absolver consultas e identificar las necesidades del los pacientes",
    "Informar y Coordinar con el cliente/paciente si hay observaciones en su solicitud",
    "Realizar otras funciones relacionadas al puesto.",
    "Tipo de trabajo",
    "Rango de horario 8am a 8pm dentro de ello habrían 2 turnos para poder rotar.",
    "Trabajo Lunes a sábado y domingo descansan",
    "Rotan cada turno pero de manera mensual ( quiere decir que les asignan un turno y estarán en ese turno 1 mes aproximadamente y luego rotan a otro de esos 3 turnos."
   ],
   "requisitos": [
    "Egresados y/o titulados de la carrera Técnico de Farmacia.",
    "Disponibilidad para laborar en turnos rotativos.",
    "Experiencia de 6 meses en boticas o Farmacias."
   ],
   "beneficios": [
    "Ingreso a planilla desde el primer día con todo los beneficios de ley al 100%.",
    "(CTS, gratificaciones, vacaciones, pago de Essalud, asignación familiar)",
    "Salario acorde al mercado",
    "Capacitaciones constantes y desarrollo de proyectos dentro del área.",
    "Salario S/1500",
    "Facilidades para adquirir productos de la empresa."
   ],
   "url": "https://www.bumeran.com.pe/empleos/tecnico-de-farmacia-para-atencion-al-cliente-cuidafarma-1118386056.html"
  },
  {
   "id": 23,
   "puesto": "Supervisor(a) de Energías Renovables",
   "empresa": "Talento Humano Perú",
   "cat": "Prácticas",
   "min": 2500,
   "max": 2500,
   "modalidad": "Presencial",
   "ciudad": "Piura",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-11-28",
   "restan": 115,
   "score": 92,
   "resumen": "Supervisar a pasantes estudiantes o profesionales extranjeros que trabajan con la ONG en campo.",
   "funciones": [
    "Supervisar a pasantes estudiantes o profesionales extranjeros que trabajan con la ONG en campo.",
    "Soporte del jefe inmediato, respecto al desarrollo de proyectos.",
    "Gestionar el desarrollo social comunitario relacionados a energías renovables."
   ],
   "requisitos": [
    "Bachiller en la carrera de Ingeniería Civil, Ingeniería Industrial, Ingeniería de Energía, Ingeniería en Energías Renovables, Ingeniería Mecánica, Ingeniería Eléctrica o carreras afines al puesto.",
    "Experiencia mínima de un (1) año en trabajos relacionados a energías renovables.",
    "Conocimiento técnico en energía solar.",
    "Conocimiento en energía eólica.",
    "Idioma inglés, nivel intermedio/avanzado."
   ],
   "beneficios": [
    "Ingreso a Planilla General, con todos los beneficios de acuerdo a Ley.",
    "Contrato de 1 año, renovable.",
    "Remuneración entre: S/. 2,500.00 soles a S/. 3,500.00 soles (De acuerdo a evaluación)",
    "Estadía, se brinda casa para empleados.",
    "Alimentación al 100%.",
    "EPS al 100% para el trabajador.",
    "Curso de inglés para nivelarse al nivel avanzado.",
    "Línea de carrera.",
    "Buen clima laboral, oficina en zona de playa.",
    "LUGAR Y HORARIO DE TRABAJO",
    "Lobitos, Talara, Piura.",
    "Lunes a viernes de 9:00 a.m. a 5:00 p.m. y sábados (eventualmente)"
   ],
   "url": "https://www.bumeran.com.pe/empleos/supervisora-de-energias-renovables-|-piura-talara-talento-humano-peru-1118386921.html"
  },
  {
   "id": 24,
   "puesto": "Operaria de Limpieza de Producción",
   "empresa": "CYL",
   "cat": "Ingeniería",
   "min": 1150,
   "max": 1150,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-09-29",
   "restan": 55,
   "score": 91,
   "resumen": "Limpiar y contar las piezas durante el proceso de producción.",
   "funciones": [
    "Limpiar y contar las piezas durante el proceso de producción.",
    "Brindar apoyo a los operarios de máquina.",
    "Mantener el orden y la limpieza del área de trabajo.",
    "Cumplir con las normas de calidad y seguridad.",
    "Desarrollar sus funciones dentro de planta."
   ],
   "requisitos": [
    "Secundaria completa",
    "Con o sin experiencia.",
    "DISPOSICIÓN PARA APRENDER Y ADAPTARSE EN EL ÁREA.",
    "Disponibilidad para realizar horas extras.",
    "Disponibilidad inmediata para laborar dentro de planta.",
    "Domingo día libre (ROTAN DE MANERA MENSUAL)",
    "Turno 1 Lunes a Viernes de 7 am a 4:15 pm y sábados de 7 am a 12:30 pm",
    "Turno 2 Lunes a Viernes de 9 am a 7:15 pm."
   ],
   "beneficios": [
    "Ingreso a planilla directo (todos los beneficios+SSALUD+ASIGNACION FAMILIAR+UTILIDADES)",
    "Bono de transporte+ bono por asistencia",
    "Estabilidad laboral",
    "Sueldo s/1150.00 aumenta al año s/1180. 00",
    "Alimentación un 70% cubierto"
   ],
   "url": "https://www.bumeran.com.pe/empleos/operaria-de-limpieza-de-produccion-ingreso-a-planillabonos-ate-cyl-1118387056.html"
  },
  {
   "id": 25,
   "puesto": "Operario de Almacén",
   "empresa": "CYL",
   "cat": "Logística",
   "min": 1150,
   "max": 1150,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-09-29",
   "restan": 55,
   "score": 91,
   "resumen": "Ejecuta la recepción, almacenamiento, picking y despacho de mercancías vinculadas a procesos de importación y exportación",
   "funciones": [
    "Ejecuta la recepción, almacenamiento, picking y despacho de mercancías vinculadas a procesos de importación y exportación",
    "Verifica cantidades, documentación y estado físico de la mercancía crítica.",
    "Registra los movimientos de ingreso, salida y ubicación de mercancías en los sistemas y formatos establecidos.",
    "Identifica, separa y reporta productos no conformes (PNC).",
    "Controla y reporta los stocks de mercancía crítica.",
    "Cumplir con las normas de calidad y seguridad y reglamento interno de trabajo dentro de la planta."
   ],
   "requisitos": [
    "Secundaria completa",
    "Experiencia 1 mes como mínimo",
    "DISPOSICIÓN PARA APRENDER Y ADAPTARSE EN EL ÁREA.",
    "Disponibilidad de horas extra",
    "TURNO: Domingo día libre (ROTAN DE MANERA MENSUAL)",
    "Turno 1 Lunes a Viernes de 7 am a 4:15 pm y sábados de 7 am a 12:30 pm",
    "Turno 2 Lunes a Viernes de 9 am a 7:15 pm."
   ],
   "beneficios": [
    "Ingreso a planilla directo (todos los beneficios+SSALUD+ASIGNACION FAMILIAR+UTILIDADES)",
    "Bono de transporte+ bono por asistencia",
    "Estabilidad laboral",
    "Sueldo s/1150.00 aumenta al año s/1180. 00",
    "Alimentación un 70% cubierto"
   ],
   "url": "https://www.bumeran.com.pe/empleos/operario-de-almacen-|-bonos-planilla-cyl-1118387057.html"
  },
  {
   "id": 26,
   "puesto": "Operario de Limpieza de Piezas-producción con",
   "empresa": "CYL",
   "cat": "Ingeniería",
   "min": 1150,
   "max": 1150,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-09-29",
   "restan": 55,
   "score": 91,
   "resumen": "¡TU OPORTUNIDAD EN PRODUCCIÓN ESTÁ AQUÍ!",
   "funciones": [
    "Limpieza y conteo de piezas durante el proceso de producción",
    "Apoyo a operarios de máquina",
    "Mantener el orden y limpieza del área de trabajo",
    "Cumplir con normas de calidad y seguridad",
    "Trabajo dentro de planta"
   ],
   "requisitos": [
    "Secundaria completa",
    "Con o sin experiencia",
    "Disponibilidad para realizar horas extras",
    "Actitud para aprender y adaptarse al área de producción",
    "Disponibilidad para turno rotativos",
    "Turno 1 Lunes a Viernes de 7 am a 4:15 pm y sábados de 7 am a 12:30 pm",
    "Turno 2 Lunes a Viernes de 9 am a 7:15 pm."
   ],
   "beneficios": [
    "Ingreso a planilla directa con todos los beneficios de ley",
    "Bono de transporte + bono por asistencia",
    "Sueldo S/ 1150.00 con incremento a S/ 1180.00 al cumplir un año",
    "Alimentación cubierta al 70%",
    "Buen clima laboral y oportunidades de crecimiento"
   ],
   "url": "https://www.bumeran.com.pe/empleos/operario-de-limpieza-de-piezas-produccion-con-sin-experiencia-ate-cyl-1118386581.html"
  },
  {
   "id": 27,
   "puesto": "Operador de Monitoreo Vehicular",
   "empresa": "Confidencial",
   "cat": "Tecnología",
   "min": 1200,
   "max": 1200,
   "modalidad": "Remoto",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 90,
   "resumen": "CERTISAT , empresa especializada en soluciones de rastreo satelital y monitoreo vehicular, se encuentra en la búsqueda de un(a) Operador(a) de Monitoreo Vehicular para integrarse a nuestro equipo.",
   "funciones": [
    "Monitorear en tiempo real la ubicación y estado de las unidades vehiculares mediante la plataforma GPS.",
    "Recepcionar, analizar y gestionar alertas generadas por el sistema (exceso de velocidad, botón de pánico, desvíos de ruta, ingreso a zonas restringidas, desconexión de equipos, entre otros).",
    "Mantener comunicación permanente con conductores y clientes para la atención de incidencias.",
    "Activar y ejecutar los protocolos de seguridad establecidos según el tipo de evento.",
    "Registrar y reportar incidencias, novedades y eventos en el sistema de monitoreo.",
    "Coordinar con las áreas correspondientes para la atención oportuna de emergencias.",
    "Elaborar reportes de monitoreo y seguimiento de eventos.",
    "Brindar soporte telefónico a clientes respecto al servicio de monitoreo.",
    "Mantener actualizada la información de las unidades y clientes en la plataforma."
   ],
   "requisitos": [
    "Experiencia mínima de 1 año en call center , central de monitoreo GPS o monitoreo vehicular.",
    "Manejo de computadoras y herramientas de Microsoft Office a nivel básico.",
    "Capacidad para trabajar bajo presión y resolver incidencias.",
    "Buena comunicación verbal y escrita.",
    "Atención al detalle y alto sentido de responsabilidad.",
    "Disponibilidad para laborar en horario de 3:00 p.m. a 11:00 p.m.",
    "Disponibilidad para trabajar con descanso rotativo ."
   ],
   "beneficios": [
    "Lugar de trabajo: San Isidro – Modalidad híbrida (presencial y remoto).",
    "Horario: 3:00 p.m. a 11:00 p.m.",
    "Descanso: Rotativo.",
    "Sueldo básico de S/ 1,200 .",
    "Bonificaciones por cumplimiento de metas.",
    "Ingreso a planilla desde el primer día.",
    "Todos los beneficios de ley.",
    "Capacitación constante.",
    "Excelente clima laboral.",
    "Oportunidad de desarrollo profesional.",
    "Si deseas formar parte de una empresa en crecimiento y contribuir a la seguridad de nuestros clientes, postula y únete a CERTISAT."
   ],
   "url": "https://www.bumeran.com.pe/empleos/operador-de-monitoreo-vehicular--central-de-monitoreo-gps-1118386543.html"
  },
  {
   "id": 28,
   "puesto": "Practicante de Soporte Técnico",
   "empresa": "BOLD ASCENT",
   "cat": "Tecnología",
   "min": 1200,
   "max": 1200,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 89,
   "resumen": "¡Únete a nuestro equipo de Soporte Técnico!",
   "funciones": [
    "Gestión de Software: Instalarás y configurarás programas de forma remota y presencial.",
    "Soporte al Usuario: Ayudarás a resolver problemas técnicos de nuestros clientes con la mejor actitud.",
    "Documentación: Apoyarás en la creación de guías y participarás en proyectos de mejora.",
    "Apoyo en Hardware: Brindarás soporte en el ensamblaje y mantenimiento preventivo de nuestros productos.",
    "Impacto Real: Participarás en proyectos con clientes internacionales desde el primer día."
   ],
   "requisitos": [
    "Educación: Estudiante (con disponibilidad de tiempo completo) o Egresado, ya sea de carrera Técnica o Universitaria en Sistemas, Informática, Computación, Redes o afines.",
    "Conocimientos: Manejo de Windows OS, instalación de software y nociones básicas/intermedias de ensamblaje de equipos de cómputo .",
    "Habilidades: Persona proactiva, con iniciativa y que disfrute el trabajo en equipo.",
    "Actitud: ¡Muchas ganas de crecer y aprender!"
   ],
   "beneficios": [
    "Línea de carrera: Posibilidad de ascender en corto plazo.",
    "Crecimiento salarial: Incrementos según tu desempeño y compromiso.",
    "Capacitación constante: uso de herramientas tecnológicas de vanguardia.",
    "Beneficios: Seguro FOLA.",
    "Ambiente: Un lugar dinámico, divertido y con excelente clima laboral."
   ],
   "url": "https://www.bumeran.com.pe/empleos/practicante-de-soporte-tecnico-bold-ascent-1118386254.html"
  },
  {
   "id": 29,
   "puesto": "Jefe de Marketing",
   "empresa": "Confidencial",
   "cat": "Marketing",
   "min": 1800,
   "max": 1800,
   "modalidad": "Presencial",
   "ciudad": "Arequipa",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-11-28",
   "restan": 115,
   "score": 89,
   "resumen": "Personal a cargo: 2 colaboradores (Edición Audiovisual y Diseño/Contenido)",
   "funciones": [
    "Asimismo, liderar al equipo de marketing y coordinar de manera transversal con los jefes de categoría para asegurar la correcta ejecución de las campañas comerciales.",
    "Estrategia de Marketing",
    "Ejecutar el plan anual y mensual de marketing.",
    "Crear campañas comerciales orientadas a incrementar el tráfico de visitantes.",
    "Diseñar estrategias para potenciar las ventas de los comercios de la galería.",
    "Desarrollar campañas para fortalecer el posicionamiento de la galería como destino comercial.",
    "Implementar campañas para atraer nuevos arrendatarios a los espacios comerciales disponibles.",
    "Definir el calendario comercial de campañas, promociones y eventos.",
    "Marketing Digital",
    "Planificar campañas para Facebook, Instagram, TikTok y otras plataformas digitales.",
    "Gestionar campañas pagadas (Meta Ads, Google Ads y TikTok Ads).",
    "Analizar métricas digitales y optimizar campañas de manera permanente."
   ],
   "requisitos": [
    "Orientación a resultados.",
    "Trabajo colaborativo.",
    "Específicas del cargo",
    "Comunicación e influencia.",
    "Análisis de datos.",
    "Orientación al cliente."
   ],
   "beneficios": [
    "Sueldo básico: S/ 1,800.00",
    "Bono variable: Hasta S/ 1,500.00 mensuales , sujeto al cumplimiento de indicadores.",
    "Ingreso a planilla desde el primer día.",
    "Régimen General (100% de beneficios de ley).",
    "Seguro EsSalud.",
    "Asignación familiar (de corresponder)."
   ],
   "url": "https://www.bumeran.com.pe/empleos/jefe-de-marketing-1118356328.html"
  },
  {
   "id": 30,
   "puesto": "Labora de Lunes a Viernes FIJO! Atención al cliente",
   "empresa": "ManpowerGroup Perú",
   "cat": "Atención al Cliente",
   "min": 2100,
   "max": 2100,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-28",
   "restan": 84,
   "score": 89,
   "resumen": "Por encargo de nuestro cliente líder, nos encontramos en búsqueda de talentos para cubrir la posición de:",
   "funciones": [
    "Resolver consultas en primera llamada",
    "Gestionar beneficios, reclamos y cuentas médicas",
    "Brindar soporte a clientes adultos estadounidenses",
    "Documentar interacciones con precisión y empatía"
   ],
   "requisitos": [
    "Secundaria completa",
    "6 meses en atención al cliente",
    "Inglés B2 – B2+ (indispensable)",
    "Manejo de Office (indispensable)",
    "100% presencial – San Borja"
   ],
   "beneficios": [
    "Sueldo: S/ 2,100",
    "Bono hasta 15%",
    "Movilidad: S/ 80",
    "Capacitación pagada: S/ 1,750 + movilidad",
    "Línea de carrera desde el mes 1",
    "Lunes a viernes (descanso fines de semana)",
    "Se pagan feriados peruanos (triple).",
    ".“En Manpower promovemos la inserción e inclusión laboral de personas con discapacidad\""
   ],
   "url": "https://www.bumeran.com.pe/empleos/labora-de-lunes-a-viernes-fijo-atencion-al-cliente-turno-manana-s.-2500-manpowergroup-peru-1118386965.html"
  },
  {
   "id": 31,
   "puesto": "Operario de Producción",
   "empresa": "CYL",
   "cat": "Ingeniería",
   "min": 1150,
   "max": 1150,
   "modalidad": "Presencial",
   "ciudad": "Lima",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-09-29",
   "restan": 55,
   "score": 89,
   "resumen": "Manejo de las máquinas de varias (anillado-habilitado-corte-caucho y operaciones manuales).",
   "funciones": [
    "Manejo de las máquinas de varias (anillado-habilitado-corte-caucho y operaciones manuales).",
    "Mantener su puesto de trabajo limpio y ordenado.",
    "Cumplir con las normas de calidad y seguridad y reglamento interno de trabajo dentro de la planta. Conocer las rutas de evacuación.",
    "Cumplir los instructivos de trabajo"
   ],
   "requisitos": [
    "Secundaria completa",
    "Experiencia 1 mes como mínimo",
    "DISPOSICIÓN PARA APRENDER Y ADAPTARSE EN EL ÁREA.",
    "Disponibilidad de horas extra",
    "TURNO: Domingo día libre (ROTAN DE MANERA MENSUAL)",
    "Turno 1 Lunes a Viernes de 7 am a 4:15 pm y sábados de 7 am a 12:30 pm",
    "Turno 2 Lunes a Viernes de 9 am a 7:15 pm."
   ],
   "beneficios": [
    "Ingreso a planilla directo (todos los beneficios+SSALUD+ASIGNACION FAMILIAR+UTILIDADES)",
    "Bono de transporte+ bono por asistencia",
    "Estabilidad laboral",
    "Sueldo s/1150.00 aumenta al año s/1180. 00",
    "Alimentación un 70% cubierto"
   ],
   "url": "https://www.bumeran.com.pe/empleos/estamos-contratando-operario-de-produccion--ate-cyl-1118387062.html"
  },
  {
   "id": 32,
   "puesto": "Practicante de Contabilidad",
   "empresa": "Confidencial",
   "cat": "Contabilidad",
   "min": 565,
   "max": 565,
   "modalidad": "Presencial",
   "ciudad": "Arequipa",
   "fuente": "Bumeran",
   "dias": 5,
   "vence": "2026-10-29",
   "restan": 85,
   "score": 87,
   "resumen": "Convocatoria – Practicante de Contabilidad",
   "funciones": [
    "Apoyo en el registro de comprobantes de compras y ventas en el sistema contable.",
    "Registro y control de caja chica.",
    "Apoyo en el análisis de cuentas contables.",
    "Organización, clasificación y archivo de documentación contable.",
    "Apoyo en la elaboración de reportes e informes contables.",
    "Verificación de documentos (facturas, recibos, entre otros).",
    "Apoyo en conciliaciones bancarias.",
    "Apoyo en el control de cuentas por pagar y cobrar.",
    "Soporte en procesos tributarios (registro de compras, ventas, detracciones, entre otros).",
    "Otras funciones asignadas por el jefe inmediato."
   ],
   "requisitos": [
    "Estudiante de últimos ciclos o egresado de Contabilidad o carreras afines.",
    "Manejo de Microsoft Office (nivel intermedio).",
    "Responsabilidad y organización.",
    "Manejo de sistemas contables.",
    "Experiencia previa mínima de 6 meses."
   ],
   "beneficios": [
    "Convenio de prácticas preprofesionales o profesionales.",
    "Certificado de prácticas.",
    "Incentivo economico .",
    "Oportunidad de aprendizaje y desarrollo profesional.",
    "Buen clima laboral.",
    "Posibilidad de línea de carrera.",
    "Lunes a viernes: 8:00 a. m. – 6:30 p. m.",
    "Sábados: 8:00 a. m. – 1:00 p. m.",
    "Envia tu CV: seleccion.mindgroup (arroba) gmail.com"
   ],
   "url": "https://www.bumeran.com.pe/empleos/practicante-de-contabilidad-1118386534.html"
  },
  {
   "id": 33,
   "puesto": "Auxiliar Administrativo",
   "empresa": "Proyecto Especial Regional Plan Copesco Del Gobierno Regional Del Cusco",
   "cat": "Tecnología",
   "min": 2100,
   "max": 2100,
   "modalidad": "Presencial",
   "ciudad": "Cusco",
   "fuente": "Convocatorias del Estado",
   "dias": 15,
   "vence": "2026-08-10",
   "restan": 5,
   "score": 84,
   "resumen": "Convocatoria para Auxiliar Administrativo en Proyecto Especial Regional Plan Copesco Del Gobierno Regional Del Cusco. Sueldo S/ 2,100. Postula antes del 10 ago. 2026. Tipo de contrato: 728.",
   "funciones": [
    "Auxiliar Administrativo - Proyecto Especial Regional Plan Copesco Del Gobierno Regional Del Cusco | Convocape | Convocape",
    "Auxiliar Administrativo"
   ],
   "requisitos": [
    "Constancia De Estudios Superiores En Derecho",
    "Experiencia Laboral Igual O Mayor A 01 Año",
    "06 Meses De Experiencia Con La Función A Desempeñar En El Área",
    "Nueva Ley De Contrataciones Con El Estado",
    "Conocimiento Del Sistema De Administración Pública",
    "Manejo De Microsoft Office",
    "Trabajo Bajo Presión, Comunicación Asertiva, Iniciativa, Responsabilidad, Capacidad De Resolver Problemas, Organización, Trabajo En Equipo Y Proactividad",
    "Disponibilidad Inmediata",
    "Especialización en Capacitación En Gestión O Administración Pública."
   ],
   "beneficios": [
    "Régimen laboral privado (D. Leg. 728): planilla con todos los beneficios de ley",
    "Gratificaciones de julio y diciembre",
    "30 días calendario de vacaciones al año",
    "Seguro de salud EsSalud y afiliación pensionaria"
   ],
   "url": "https://www.convocape.com/convocatorias/auxiliar-administrativo-proyecto-especial-regional-plan-copesco-del-gobierno-regional-del-cusco-728-2026-07-797486"
  }
 ]
};
